version: "3"

services:
  backend:
    image: wms2537/nodejs-jwt-auth:${BUILD_NUMBER}
    expose: 
      - 80
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      NUM_KEYS: 5
      VIRTUAL_HOST: auth.wmtech.cc
      LETSENCRYPT_HOST: auth.wmtech.cc
      LETSENCRYPT_EMAIL: swmeng@yes.my
    restart: unless-stopped
    container_name: auth-nodejs-backend


networks:
  default:
    external:
      name: nginx-proxy